In [1]:
import numpy as np
from __future__ import annotations

In [89]:
class Linear:
    def __init__(self, in_features: int, out_features: int):
        # xavier-like normalization
        limit = 1/np.sqrt(in_features)
        self._w = np.random.uniform(-limit, limit, (in_features, out_features))
        self._b = np.zeros(out_features)
        
    def __call__(self, X):
        return X @ self._w + self._b

    def parameters(self):
        return [self._w , self._b]

In [90]:
x = np.random.randint(0, 10, (10, 4))
layer_1 = Linear(in_features=4, out_features=5)
layer_1.parameters()

[array([[ 0.09261279, -0.08939693,  0.39080986, -0.36968964, -0.38725701],
        [ 0.1373715 ,  0.49090952, -0.34931418,  0.3214125 ,  0.04609815],
        [ 0.04857587, -0.45372318,  0.26719328,  0.1440953 , -0.36884468],
        [ 0.37208482, -0.21292918,  0.09326561, -0.13508157, -0.41063224]]),
 array([0., 0., 0., 0., 0.])]

In [198]:
class MLP:
    def __init__(self, in_features: int, layer_outfeatures: List):
        z = [in_features] + layer_outfeatures
        self.layers = [Linear(z[i], z[i+1]) for i in range(len(layer_outfeatures))]

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

    def parameters(self):
        count = 0
        for layer in self.layers:
            count += sum([len(i) for i in layer.parameters()])
        return count

    def summary(self, sample: array):
        layers = self.layers
        header = ['Name', 'Type', 'Shape', 'Trainable', 'Param #']
        data = [] 
        footer = {'Total Params': 0, 'Trainable': 0, 'Non-Trainable': 0}
        
        for n, l in enumerate(layers):
            op = l(sample)
            name = layer_1.__class__.__name__
            data.append([f'Layer_{n+1}', name, op.shape, 'True', self.parameters()])
            footer['Total Params'] += self.parameters()
            footer['Trainable'] += self.parameters()
            footer['Non-Trainable'] += footer['Total Params'] - footer['Trainable']

        # printing
        col_widths = [max(len(str(row[i])) for row in [header] + data) for i in range(len(header))]
        # header
        print("  ".join(str(header[i]).ljust(col_widths[i]) for i in range(len(header))))
        print("-" * (sum(col_widths) + 2 * (len(header) - 1)))
        # data
        for row in data:
            print("  ".join(str(item).ljust(col_widths[i]) for i, item in enumerate(row)))
        print("-" * (sum(col_widths) + 2 * (len(header) - 1)))
        # footer
        for x in footer.items():
            print(x[0],':', x[1])
            

In [199]:
x = [3.0, 2.2, 1.3, 4.5]
x = np.asarray(x)
layers = MLP(4, [4, 4, 1])
layers(x)

array([-0.06603216])

In [200]:
layers.parameters()

21

In [201]:
layer_1.parameters()

[array([[ 0.09261279, -0.08939693,  0.39080986, -0.36968964, -0.38725701],
        [ 0.1373715 ,  0.49090952, -0.34931418,  0.3214125 ,  0.04609815],
        [ 0.04857587, -0.45372318,  0.26719328,  0.1440953 , -0.36884468],
        [ 0.37208482, -0.21292918,  0.09326561, -0.13508157, -0.41063224]]),
 array([0., 0., 0., 0., 0.])]

In [197]:
layers.summary(x)

Name     Type    Shape  Trainable  Param #
------------------------------------------
Layer_1  Linear  (4,)   True       21     
Layer_2  Linear  (4,)   True       21     
Layer_3  Linear  (1,)   True       21     
------------------------------------------
Total Params : 63
Trainable : 63
Non-Trainable : 0
